### ISSUE TITLE
Forking / Reusing code for local communities 

### ISSUE THREAD

**Issue by jrgabler** [emergentworks/project-not-911#47]
Not an issue, but I wanted to know if I could fork / use this codebase as a launching point for my local community (Rochester, NY). I think this is a great idea and the community could definitely use this service right now. We currently have images going around with the resources, but that is not always comprehensive or accurate.

It’s my intention to reach out to knowledgeable people in Rochester to verify the local sources as well as other members in the community to help customize it for local services.

**Comment by mhelmetag** [comment]
I'd vote for something more centralized. That way the app and pwa could stay similar (one app that can service all areas).

The location specific info could be done in markdown or json. Or, if you wanted to get fancier, a headless CMS (like strapi or something).

**Comment by rossPatton** [comment]
Go for it! It's open source of course - so feel free to do whatever you want with it - forking, doesn't matter to us!

However, we just had a meeting to figure out ongoing support for this project, and other cities came up as a requested feature. We do want to eventually support multiple cities within the not911 app, like @mhelmetag suggested. 

Any little bit of contribution is appreciated!
