### ISSUE TITLE
not911 should serve multiple cities in the US (or world?)

### ISSUE THREAD

**Issue by rossPatton** [emergentworks/project-not-911#49]
Currently not911 is entirely focused on NYC and NY state based services

Ideally, not911 would be available in as many cities as possible

At the moment, we don't have a list of desired cities, we'll take any contributions that come our way

But once we've established what a multiple city app looks like - we will want to plan out expansion (should we focus on cities with good police alternative programs? or should we focus on population? or cities where police are particularly violent?)

**Comment by mhelmetag** [comment]
I was listening to Jamstack Conf and there was a presentation from a dev at the ACLU talking about this site https://www.aclu.org/voter. Seemed like it fit a similar paradigm (providing state specific information; which could be broken down further to city specific).

Just thought of this project and the goal to reach more than NYC, and thought this ACLU site was a good example.

**Comment by rossPatton** [comment]
we actually just added support for multiple cities, and we plan to rapidly expand our list of cities here soon. definitely want to reach out to existing networks and possibly combine our efforts

but for now, i think we can close this issue (i will replace it with a new one - expanding our coverage)
