### ISSUE TITLE
A More Beginner-Friendly Steps to Run the Project 

### ISSUE THREAD

**Issue by RodolfoNei** [emergentworks/project-not-911#53]
Hello!

I was recently aware of the project-not-911 and I found some issues setting up the project that could be troublesome to beginners like me, especially with the Expo commands and the git clone link, that has SSH keys as a premise the way it is now.

I figured out my way in and I would like to send a PR with some ideas in the coming days!

**Comment by rossPatton** [comment]
Sorry for my slow response. Documentation is hard! And it's always good to have a beginner's perspective on it. I'm open to anything you think will make the project easier for folks to setup!

**Comment by rossPatton** [comment]
Just saw your PR - a few comments for you there
